steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
        "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest",
        "."
      ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}"
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",

        "--port", "8080",
        "--memory", "512Mi",
        "--cpu", "1",
        "--timeout", "300",

        "--max-instances", "20",
        "--min-instances", "0",

        # 🚀 Fast cold starts (free)
        "--cpu-boost",
        "--startup-cpu-boost",

        # ✔ Cloud Run will not route traffic until app is actually ready
        "--readiness-check-path=/health/ready",

        # ⏳ Allow slow dependencies during cold start
        "--startup-timeout=300"
      ]

substitutions:
  _REGION: "europe-west1"
  _REPOSITORY: "spoonit-backend"
  _SERVICE_NAME: "spoonitbackend"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
