import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:developer' as developer;

class ShoppingItem {
  final String id;
  final String name;
  final bool isChecked;
  final DateTime createdAt;

  ShoppingItem({
    required this.id,
    required this.name,
    this.isChecked = false,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  Map<String, dynamic> toFirestore() {
    return {
      'name': name,
      'isChecked': isChecked,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }

  factory ShoppingItem.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ShoppingItem(
      id: doc.id,
      name: data['name'] ?? '',
      isChecked: data['isChecked'] ?? false,
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  ShoppingItem copyWith({
    String? id,
    String? name,
    bool? isChecked,
    DateTime? createdAt,
  }) {
    return ShoppingItem(
      id: id ?? this.id,
      name: name ?? this.name,
      isChecked: isChecked ?? this.isChecked,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}

class ShoppingListService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Get shopping list items for a user
  Stream<List<ShoppingItem>> getShoppingList(String userId) {
    developer.log(
      'Getting shopping list for user: $userId',
      name: 'ShoppingListService',
    );

    return _firestore
        .collection('users')
        .doc(userId)
        .collection('shoppingList')
        .orderBy('createdAt', descending: false)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => ShoppingItem.fromFirestore(doc))
              .toList();
        });
  }

  // Get current item count
  Future<int> getItemCount(String userId) async {
    try {
      final snapshot =
          await _firestore
              .collection('users')
              .doc(userId)
              .collection('shoppingList')
              .get();

      return snapshot.docs.length;
    } catch (e) {
      developer.log(
        'Error getting item count: $e',
        name: 'ShoppingListService',
      );
      return 0;
    }
  }

  // Add item to shopping list
  Future<void> addItem(String userId, String itemName) async {
    try {
      developer.log(
        'Adding item to shopping list: $itemName',
        name: 'ShoppingListService',
      );

      // Check current item count
      final currentCount = await getItemCount(userId);
      if (currentCount >= 100) {
        developer.log(
          'Shopping list limit reached (100 items)',
          name: 'ShoppingListService',
        );
        throw Exception('Shopping list limit reached (100 items)');
      }

      // Check if item already exists
      final existingItems =
          await _firestore
              .collection('users')
              .doc(userId)
              .collection('shoppingList')
              .where('name', isEqualTo: itemName)
              .get();

      if (existingItems.docs.isNotEmpty) {
        developer.log(
          'Item already exists in shopping list',
          name: 'ShoppingListService',
        );
        throw Exception('Item already exists');
      }

      final item = ShoppingItem(
        id: '', // Will be generated by Firestore
        name: itemName,
      );

      await _firestore
          .collection('users')
          .doc(userId)
          .collection('shoppingList')
          .add(item.toFirestore());

      developer.log('Item added successfully', name: 'ShoppingListService');
    } catch (e, stackTrace) {
      developer.log(
        'Error adding item to shopping list: $e',
        name: 'ShoppingListService',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  // Update item (toggle checked status)
  Future<void> updateItem(String userId, String itemId, bool isChecked) async {
    try {
      developer.log(
        'Updating item: $itemId, checked: $isChecked',
        name: 'ShoppingListService',
      );

      await _firestore
          .collection('users')
          .doc(userId)
          .collection('shoppingList')
          .doc(itemId)
          .update({'isChecked': isChecked});

      developer.log('Item updated successfully', name: 'ShoppingListService');
    } catch (e, stackTrace) {
      developer.log(
        'Error updating item: $e',
        name: 'ShoppingListService',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  // Delete item
  Future<void> deleteItem(String userId, String itemId) async {
    try {
      developer.log('Deleting item: $itemId', name: 'ShoppingListService');

      await _firestore
          .collection('users')
          .doc(userId)
          .collection('shoppingList')
          .doc(itemId)
          .delete();

      developer.log('Item deleted successfully', name: 'ShoppingListService');
    } catch (e, stackTrace) {
      developer.log(
        'Error deleting item: $e',
        name: 'ShoppingListService',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  // Clear all checked items
  Future<void> clearCheckedItems(String userId) async {
    try {
      developer.log('Clearing checked items', name: 'ShoppingListService');

      final checkedItems =
          await _firestore
              .collection('users')
              .doc(userId)
              .collection('shoppingList')
              .where('isChecked', isEqualTo: true)
              .get();

      final batch = _firestore.batch();
      for (final doc in checkedItems.docs) {
        batch.delete(doc.reference);
      }

      await batch.commit();
      developer.log(
        'Checked items cleared successfully',
        name: 'ShoppingListService',
      );
    } catch (e, stackTrace) {
      developer.log(
        'Error clearing checked items: $e',
        name: 'ShoppingListService',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  // Check if item exists
  Future<bool> itemExists(String userId, String itemName) async {
    try {
      final existingItems =
          await _firestore
              .collection('users')
              .doc(userId)
              .collection('shoppingList')
              .where('name', isEqualTo: itemName)
              .get();

      return existingItems.docs.isNotEmpty;
    } catch (e) {
      developer.log(
        'Error checking if item exists: $e',
        name: 'ShoppingListService',
        error: e,
      );
      return false;
    }
  }
}
