// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUayJmryFpuzRbiY_W_1D3bx2wkzNRn2Y',
    appId: '1:682017024777:web:b53ab4e1120a5e2f8601d8',
    messagingSenderId: '682017024777',
    projectId: 'recipekeeper-d436a',
    authDomain: 'recipekeeper-d436a.firebaseapp.com',
    storageBucket: 'recipekeeper-d436a.firebasestorage.app',
    measurementId: 'G-7XZD3KWERF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXQk04xVWZfkAwUYsYUE2_-cqoP7QYfY',
    appId: '1:682017024777:android:60351fed0ebb4eab8601d8',
    messagingSenderId: '682017024777',
    projectId: 'recipekeeper-d436a',
    storageBucket: 'recipekeeper-d436a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4cqRs1vAHcb9jSeXjo-FMysj3wMHSqI',
    appId: '1:682017024777:ios:c48cb71f25c5d4608601d8',
    messagingSenderId: '682017024777',
    projectId: 'recipekeeper-d436a',
    storageBucket: 'recipekeeper-d436a.firebasestorage.app',
    iosClientId: '682017024777-on5ondrk2tinfabj0b4smecc16jpbuo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4cqRs1vAHcb9jSeXjo-FMysj3wMHSqI',
    appId: '1:682017024777:ios:c48cb71f25c5d4608601d8',
    messagingSenderId: '682017024777',
    projectId: 'recipekeeper-d436a',
    storageBucket: 'recipekeeper-d436a.firebasestorage.app',
    iosClientId: '682017024777-on5ondrk2tinfabj0b4smecc16jpbuo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUayJmryFpuzRbiY_W_1D3bx2wkzNRn2Y',
    appId: '1:682017024777:web:e0dfe13f7c1c26368601d8',
    messagingSenderId: '682017024777',
    projectId: 'recipekeeper-d436a',
    authDomain: 'recipekeeper-d436a.firebaseapp.com',
    storageBucket: 'recipekeeper-d436a.firebasestorage.app',
    measurementId: 'G-F3W48E32Z1',
  );
}
